title: techmunchies
email: mario@techmunchies.net
description: >-
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: ""
url: ""
twitter_username: jekyllrb
github_username:  mariolopjr

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
gems: [bourbon, neat]

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
